# cookie1psid (__Secure-1PSID), cookie1psidts (__Secure-1PSIDTS) and cookie1psidcc (__Secure-1PSIDCC)
# are obtained from an active browser session with Bard open.
# obtain cookies from developer tools. If you don't know how, follow this guide:
# https://developer.chrome.com/docs/devtools/application/cookies/
# the format of the value will look like this:
# cookie1psid: "LONGSTRING-?-LONGSTRING.
cookie1psid: "" # cookie1psid is an alias to the previous "cookie" value. don't use both
cookie1psidts: ""
cookie1psidcc: ""
log_level: warn
